FROM nvcr.io/nvidia/pytorch:25.09-py3
RUN cd /workspace/ && \
    git clone https://github.com/comfyanonymous/ComfyUI.git && \
    cd ComfyUI && \
    git checkout 4ffea0e864275301329ddb5ecc3fbc7211d7a802 && \
    sed -i '/torch/d' requirements.txt && \
    pip install -r requirements.txt && \
    pip install torchsde
WORKDIR /workspace/ComfyUI
CMD ["/bin/bash"]
