FROM nvcr.io/nvidia/pytorch:25.09-py3
RUN cd /workspace/ && \
    git clone https://github.com/kohya-ss/sd-scripts.git && \
    cd sd-scripts && \
    git checkout sd3 && \
    pip install -r requirements.txt && \
    apt update && \
    apt install -y libgl1-mesa-dev
WORKDIR /workspace/sd-scripts
CMD ["/bin/bash"]
