name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]

jobs:
  authorize:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'ok-to-test'))
    steps:
      - run: echo "Build authorized"

  nixbuild:
    needs: authorize
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v24
    with:
      filter_builds: >
        .top_attr == "checks" or .top_attr == "packages"
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
